nav:
  Home: /
  About: /about/
  Blog: /archives/
  Projects: http://github.com/tyndallm

projects_url: http://github.com/tyndallm

customize:
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop: /images/favicon.ico
      android: /images/favicon-192x192.png
      apple: /images/apple-touch-icon.png
    social_links:
        github: http://github.com/tyndallm
        twitter: http://twitter.com/matrick
        facebook: https://facebook.com/tyndall
        linkedin: https://www.linkedin.com/in/tyndallm
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-93516561-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
