nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/probberechts

projects_url: http://github.com/probberechts

customize:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop: /images/favicon.ico
      android: /images/favicon-192x192.png
      apple: /images/apple-touch-icon.png
    social_links:
        github: http://github.com/probberechts/cactus-dark
        twitter: /
        facebook: /
        linkedin: /
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
